//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wc.rc
//
#define IDS_TAB1                        1
#define IDS_TAB2                        2
#define IDS_TAB3                        3
#define IDS_TAB4                        4
#define IDI_00MAIN                      101
#define IDI_01ANIM                      102
#define IDI_02ANIM                      103
#define IDI_03ANIM                      104
#define IDI_04ANIM                      105
#define IDI_05STOP                      106
#define IDI_20CATALOG                   107
#define IDI_11CONFIG                    108
#define IDD_MAIN                        111
#define IDD_WAIT                        112
#define IDD_COMMON                      113
#define IDD_KOBETSU                     114
#define IDD_LIST                        115
#define IDD_PLUGIN                      116
#define IDR_ACCEL1                      120
#define IDR_CONFIG_ADD                  130
#define IDR_CATALOG                     131
#define IDR_CONFIG_DELETE               132
#define IDR_CONFIG_FILE                 133
#define IDR_CONFIG_LISTVIEW             134
#define IDR_WC_MAIN                     135
#define IDR_CONFIG_MOVE                 136
#define IDR_PLUGIN_LISTVIEW             137
#define IDL_ADDTION                     1001
#define IDL_COM_LIST                    1002
#define IDL_CONFIG                      1003
#define IDL_DELETE                      1004
#define IDL_EDIT                        1005
#define IDL_FILE                        1006
#define IDL_LIST                        1007
#define IDL_MOVE                        1008
#define IDL_OPTION1                     1009
#define IDL_OPTION2                     1010
#define IDL_PREVIEW                     1011
#define ID_EDIT_TIMEVAL                 1012
#define ID_EDIT_WIDTH                   1013
#define ID_COMBO_TIME                   1015
#define IDP_LIST                        1016
#define IDP_SEARCHDIR                   1017
#define IDP_CHANGEDIR                   1018
#define IDM_TAB                         1019
#define IDM_SAVE                        1020
#define IDC_TEXT                        1021
#define IDC_PROGRESS                    1022
#define ID_EDIT_HEIGHT                  1023
#define ID_COMBO_UNIT                   1024
#define ID_LABEL_WIDTH                  1025
#define ID_LABEL_HEIGHT                 1026
#define ID_LABEL_COLOR                  1027
#define ID_BUTTON_FLAG                  1028
#define ID_STATIC_PREVIEW               1029
#define ID_COMBO_EXT                    1030
#define ID_COMBO_2CLK                   1031
#define ID_BUTTON_TRANS                 1032
#define ID_BUTTON_COLSEL                1033
#define ID_STATIC_COLOR                 1034
#define IDC_SPIN_HEGHT                  1035
#define IDC_SPIN_WIDTH                  1036
#define IDC_SPIN_TIME                   1037
#define IDC_SPIN_HEIGHT                 1038
#define IDC_SPIN_NEXT                   1039
#define ID_EDIT_EXEC                    1040
#define ID_BUTTON_BROWSE                1041
#define ID_COMBO_TILE                   1042
#define IDC_COMBO1                      1155
#define IDC_COMBO2                      1156
#define IDC_RADIO1                      1157
#define IDC_RADIO2                      1158
#define ID_MNU_CONFIG                   40001
#define ID_MNU_SOON                     40002
#define ID_MNU_VERSION                  40003
#define ID_MNU_STOP                     40004
#define ID_MNU_EXIT                     40005
#define ID_MNU2_EXPLORER                40006
#define ID_MNU2_PREVIEW                 40007
#define ID_MNU2_SETNEXT                 40008
#define ID_MNU3_CONFIG                  40009
#define ID_MNU3_ORG                     40010
#define ID_MNU3_ADD                     40011
#define ID_MNU3_DEL                     40012
#define ID_MNU3_SELECTALL               40013
#define ID_MNU3_SELCHANGE               40014
#define IDM_FILE_OPEN                   40015
#define IDM_FILE_NEW                    40016
#define IDM_FILE_SAVE                   40017
#define IDM_FILE_SAVEAS                 40018
#define IDM_ADD_PICTURE                 40019
#define IDM_ADD_ARCHIVE                 40020
#define IDM_SUM_FOLDER                  40021
#define IDM_SUM_ARCHIVE                 40022
#define IDM_SUM_LIST                    40023
#define IDM_DEL_SELECTED                40024
#define IDM_DEL_ALL                     40025
#define IDM_DEL_NOT                     40026
#define IDM_MOV_DOWN                    40027
#define IDM_MOV_FLOOR                   40028
#define IDM_MOV_UP                      40029
#define IDM_MOV_CEIL                    40030
#define IDA_CTRL_P                      40040
#define IDA_ESC                         40041
#define IDA_SHIFT_F                     40042
#define IDA_SHIFT_A                     40043
#define IDA_SHIFT_L                     40044
#define IDA_CTRL_UP                     40045
#define IDA_CTRL_DOWN                   40046
#define IDA_CTRL_HOME                   40047
#define IDA_CTRL_END                    40048
#define IDA_CTRL_A                      40049
#define IDA_DELETE                      40050
#define IDA_CTRL_N                      40051
#define IDA_CTRL_O                      40052
#define IDA_CTRL_S                      40053
#define IDA_INSERT                      40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1159
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
